# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Theophrastus-Stiftung
email: info@theophrastus-stiftung.de
description: > # this means to ignore newlines until "baseurl:"
   Theophrastus-Stiftung - Dornwegshöhstr. 6 - 64367 Mühltal - Tel.: (+49) 0 6151 - 91 31 00 - Fax: (+49) 0 6151/14 86 89 - info@theophrastus-stiftung.de
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.theophrastus-stiftung.de" # the base hostname & protocol for your site
github_username:  theophrastus-stiftung
#gems: [jekyll-image-set]

# Build settings
markdown: kramdown
theme: minima
